GET http://localhost:3001/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impob25ueWJveTEyMyIsImlkIjoiNjIyNzcyZjdlNmMwYTJkNTk1NzdiOGFmIiwiaWF0IjoxNjQ2Nzc5OTg1LCJleHAiOjE2NDczODQ3ODV9.H2Fit7erdWMjb6id6o87tcxCx2JXAmUwY14FO0pqGRU

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "jhonnyboy123",
    "password": "hunter22",
    "name": "John Doe"
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "jhonnyboy123",
    "password": "hunter22"
}